### ISSUE TITLE
bbox parameter spanning more than 180° match incorrectly

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap-API#106]
It seems mongodb is wrapping polygons around the world. This matches incorrectly for requests spanning more than half the earth:

https://api.opensensemap.org/boxes/data?phenomenon=Temperatur&bbox=-180,-90,180,90

**Comment by ubergesundheit** [comment]
Seems to be fixed magically in `development`.

https://api.osem.vo1d.space/boxes/data?phenomenon=Temperatur&bbox=-180,-90,180,90

Please reopen after next merge to `master`

**Comment by noerw** [comment]
Still not working :^(
