### ISSUE TITLE
Does it make sense to attach height from box to measurements without height?

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap-API#109]
@noerw 
Imagine the following situation: A box has a location with height and measurements with locations without height. Does it make sense to attach the height of the box location to the locations without height? I think no because the height is optional.
See:
https://github.com/sensebox/openSenseMap-API/blob/a736bf4a514e7a46f7f22d7567bbf522e0de8471/lib/models/box.js#L636-L662

I would change the for loop section to:
```javascript
const originalMeasurementLocation = {};
if (data.location) {
  const { coordinates: [ lon, lat, height ] } = data.location;
  Object.assign(originalMeasurementLocation, { lon, lat, height });
}

// add all queried columns to the result
for (const col of columns) {
  if (theData[col]) {
    continue;
  }

  // assign lon, lat and height from the measurements location if availiable
  // if not, fall back to box location
  if (['lon', 'lat', 'height'].includes(col) && data.location) {
    theData[col] = originalMeasurementLocation[col];
    continue;
  }
  theData[col] = sensors[data.sensor_id][col];
}
```

**Comment by noerw** [comment]
imo you're right; if no location is provided, I would interpret that as 'no information available', so the box location could incorrect in that case.
Your for loop is far more elegant as well ;)

**Comment by ubergesundheit** [comment]
Ok. I'll leave it as already committed
