### ISSUE TITLE
Search API for senseBoxes

### ISSUE THREAD

**Issue by dbaelz** [sensebox/openSenseMap-API#119]
Just another idea to improve the API: The opensensemap.org website provides a search by `name` to find a senseBox. It would be great if this functionality is also provided by the API.

Currently, all external user of the API must fetch all senseBoxes and filter them locally. Maybe an additional query parameter for this call is sufficient. As extension search for other fields like the `description` could be provided.

**Comment by ubergesundheit** [comment]
Good suggestion!

**Comment by mpfeil** [comment]
Hi @dbaelz. I am back working more or less full-time on openSenseMap and the API.
Checkout PR https://github.com/sensebox/openSenseMap-API/pull/502 for this new feature you suggested long time ago ;)
