### ISSUE TITLE
Luftdaten: sensors "PMS"-series  "P0" bin (1.0µg/m³)  (PMS7003 et al) not displayed

### ISSUE THREAD

**Issue by Adorfer** [sensebox/openSenseMap-API#120]
Debug example: 

```
## Sending to opensensemap:
Start connecting to ingress.opensensemap.org
Requesting URL: /boxes/59ee58a9215fb80000facfffb/data?luftdaten=1
5369044
{"software_version": "NRZ-2017-099", "sensordatavalues":[{"value_type":"PMS_P0","value":"1.00"},{"value_type":"PMS_P1","value":"2.00"},{"value_type":"PMS_P2","value":"2.00"},{"value_type":"BME280_temperature","value":"24.98"},{"value_type":"BME280_humidity","value":"39.60"},{"value_type":"BME280_pressure","value":"100520.25"},{"value_type":"samples","value":"580590"},{"value_type":"min_micro","value":"216"},{"value_type":"max_micro","value":"3503442"},{"value_type":"signal","value":"-38"}]}

closing connection
```

i am not sure where to add it, otherwise i would make a PR myself. Sorry for that. 
probably it's more than one place. 

Another sensor: 
https://opensensemap.org/explore/59eb9c3b49f6f80011ade240

**Comment by ubergesundheit** [comment]
Hi,

thanks for creating the issue. You are right by assuming that there are several places that need changes.

I need the required information, or you could create the files yourself:

First: The sensor needs to be added as new file to https://github.com/sensebox/openSenseMap-API/tree/master/lib/sensorLayouts/sensorDefinitions  named `sensormodel_phenomenon.js`. The file should contain the following data:
```
title: 'the phenomenon measured, preferrably in german (this will be fixed later)',
unit: 'the unit',
sensorType: 'the model of the sensor (for example DHT22, SDS011, ...)',
icon: 'osem-your icon'
```
Possible icons: see [here](https://github.com/sensebox/openSenseMap/blob/master/app/scripts/services/sensoricons.js)

Second: `require` and `export` the newly created file in https://github.com/sensebox/openSenseMap-API/blob/master/lib/sensorLayouts/sensorDefinitions/index.js

Third: Add a new file describing the model to https://github.com/sensebox/openSenseMap-API/tree/master/lib/sensorLayouts/ (I think it should be in the `luftdaten` folder?)

Fourth: Add your new model to the `modelDefinitions` in `https://github.com/sensebox/openSenseMap-API/blob/master/lib/sensorLayouts/index.js#L22`

Fifth: Add your new model to the Frontend: https://github.com/sensebox/openSenseMap/blob/master/app/views/register.html#L162-L196

**Comment by Adorfer** [comment]
https://github.com/sensebox/openSenseMap-API/pull/121

i am not shure where the link between those are made: 
{"value_type":"PMS_P0","value":"1.00"},
{"value_type":"PMS_P1","value":"2.00"},
{"value_type":"PMS_P2","value":"2.00"},

Or has this declaration to be made different for that?  (since SDS011 is referenced as SDS011 nearly everwhere, but the sensor is sending SDS_P1 etc)

**Comment by ubergesundheit** [comment]
Ok now that #121 is merged to `development`, the next time I'll merge `development` into `master`, your changes will be deployed to opensensemap.org.

Your changes to the api will be live later on api.osem.vo1d.space

**Comment by Adorfer** [comment]
So what would be the next steps? In other words: What can i do next?
I am not quite familiar with the toolchain, in order to validate the modifications.

**Comment by ubergesundheit** [comment]
You could add tests testing your changes or you could try to register new boxes through curl on api.osem.vo1d.space and use a self compiled version of the Airrohr firmware (with api.osem.vo1d.space as openSenseMap url) to check if the values can be received.

I'll now validate your pull request to the frontend and merge it to development if no further changes are needed. When the frontend is online on the staging server and no further problems arise, I'll merge both the frontend and this repository to their respective master branches.

**Comment by ubergesundheit** [comment]
The changes are now online

**Comment by Adorfer** [comment]
as a feedback, it looks very good (PMS7003 with BME280). 
![grafik](https://user-images.githubusercontent.com/10302493/33175541-5eeb21ce-d05c-11e7-8c5c-7ee9592965b4.png)
