### ISSUE TITLE
Filter does not work properly

### ISSUE THREAD

**Issue by robarto** [sensebox/openSenseMap-API#134]
While filtering PM10 sensors, I found plenty of senseBoxes selected that do not have a PM10 sensor at all. e.g. this one: 
![filter_pm10 1](https://user-images.githubusercontent.com/3996475/35321737-fdb2d444-00e7-11e8-962c-b0f8e00f0ae1.jpeg)

**Comment by ubergesundheit** [comment]
cc @mpfeil

**Comment by mpfeil** [comment]
should be fixed with v1.2.1 of openSenseMap
