### ISSUE TITLE
change name of columns in CSV-download

### ISSUE THREAD

**Issue by robarto** [sensebox/openSenseMap-API#140]
suggestion for new names of columns that helps in understanding AND makes the file better reusable in other systems:

for monthly average:
phenomenon_year_month
for daily 
phenomenon_year_month_day
for hourly
phenomenon_year_month_day_hour   (NOT MINUTE)

**Comment by ubergesundheit** [comment]
To honour the timestamp format used everywhere else in the api, timestamps will be in truncated ISO 8601 with Z as UTC indicator format:

monthly:
`phenomenon_yyyy-mmZ`
daily:
`phenomenon_yyyy-mm-ddZ`
hourly:
`phenomenon_yyyy-mm-ddThhZ`
minutely:
`phenomenon_yyyy-mm-ddThh:mmZ`

Everything inbetween, (the api lets you specify arbitrary windows in millisecond granularity) will be computed dynamically to match the needed resolution
