### ISSUE TITLE
provide alternative CSV structure for /statistics/descriptive

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap-API#145]
The current format is useful for analysis in GIS, where rows represent geographic features.

In applications where focus of analysis is on the timeseries, a different format would be useful: Each aggregate value has its own row, with a single `time` column. An example CSV is attached.

This format simplifies timeseries analysis in R a lot, especially as the resulting data format would be ["tidy"](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html#tidy-data) in the language of R people.

[osem_download_example.csv.zip](https://github.com/sensebox/openSenseMap-API/files/1714467/osem_download_example.csv.zip)

**Comment by ubergesundheit** [comment]
Will try to deploy tomorrow (2018-03-04) or next tuesday (2018-03-06)!
