### ISSUE TITLE
Using CURL for sign-in

### ISSUE THREAD

**Issue by nobodyinperson** [sensebox/openSenseMap-API#157]
## Expected Behavior

Signing-in via `curl --data-urlencode "email=$SENSEMAP_USER" --data-urlencode "password=$SENSEMAP_PASS" https://api.opensensemap.org/users/sign-in` should return  a valid JSON Web Token as explained in the documentation:

![bildschirmfoto_2018-04-02_17-00-47](https://user-images.githubusercontent.com/19148271/38201191-a35a3c2c-3697-11e8-91c4-800b5c18e405.png)

## Current Behavior

Attempts to sign in via `curl` yield `Bad Request`.

## Possible Solution

The `curl` syntax is just wrong and should be adjusted.

## Steps to Reproduce (for bugs)

Issuing `curl --data-urlencode "email=$SENSEMAP_USER" --data-urlencode "password=$SENSEMAP_PASS" https://api.opensensemap.org/users/sign-in` yields `Bad Request`.

Same for `wget -qO- --post-data "email=$SENSEMAP_USER&password=$SENSEMAP_PASS" https://api.opensensemap.org/users/sign-in`.

Same for Python:

```python
import os, requests
r=requests.post(
    "https://api.opensensemap.org/users/sign-in",
    data={
        "email": os.environ.get("SENSEMAP_USER"), 
        "password": os.environ.get("SENSEMAP_PASS")}
)
print(r.status_code, r.reason)
# 400 Bad Request
```

## Context

Just trying to understand the API.

## Your Environment

* Operating System and version: XUbunu 16.04

**Comment by nobodyinperson** [comment]
I somehow missed the information that the fields should not be passed to the API via HTTP forms but instead just as JSON...

This works:

```bash
curl \
    -H "Content-Type: application/json" \
    -d '{"email":"'$SENSEMAP_USER'","password":"'$SENSEMAP_PASS'"}' \
    https://api.opensensemap.org/users/sign-in
```

Maybe a small note on that on the to of the documentation would be nice :-)

Great work by the way and keep it up!!

Yann

**Comment by ubergesundheit** [comment]
Good suggestion! I'll update!
