### ISSUE TITLE
Provide default value for serial port at particle sensor registration

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/openSenseMap-API#166]
During registration of a new senseBox:home with additional SDS011 sensor, you have to select a serial port where the sensor is connected to. If you don't choose anything the value remains undefined and will cause an error in the generated Arduino script. 
Please provide `Serial1` as default value.

**Comment by mpfeil** [comment]
`Serial1` is already defined as default and selected in the frontend.
https://github.com/sensebox/openSenseMap/blob/master/app/scripts/controllers/register.js#L21

Maybe you can provide more information about the environment where it is not working.
