### ISSUE TITLE
Docs: Updating/adding sensors of a senseBox via the API

### ISSUE THREAD

**Issue by nobodyinperson** [sensebox/openSenseMap-API#167]
It seems that it is not possible to update senseBox sensor metadata via the API following [the docs](https://docs.opensensemap.org/#api-Boxes-updateBox). Adding new sensors to an existing senseBox seems also not possible. Via the OpenSenseMap interface it works.

For example, if I want to change the sensor title of my test box with id `5b6af9ba9c13510019d45459` from `co2 concentration` to `SOME OTHER TITLE`, I issue a `PUT` request to `/boxes/5b6af9ba9c13510019d45459` (of course with the correct Authorization header) with this payload: 

```json
{
    "_id": "5b6af9ba9c13510019d45459",
    "exposure": "mobile",
    "grouptag": "co2mofetten",
    "location": {
        "height": 341.9,
        "lat": 48.527146,
        "lng": 9.059392
    },
    "name": "CO2 Test Box",
    "sensors": [
        {
            "_id": "5b6af9ba9c13510019d4545a",
            "icon": "osem-shock",
            "sensorType": "SenseAir LP8",
            "title": "SOME OTHER TITLE",
            "unit": "ppm"
        }
    ]
}
```
If I am not mistaken, this is the format specified by [the docs](https://docs.opensensemap.org/#api-Boxes-updateBox). The response is 

```json
{
    "code": "Ok",
    "data": {
        "_id": "5b6af9ba9c13510019d45459",
        "createdAt": "2018-08-08T14:10:02.315Z",
        "currentLocation": {
            "coordinates": [
                9.059392,
                48.527146,
                341.9
            ],
            "timestamp": "2018-08-08T15:26:54.745Z",
            "type": "Point"
        },
        "exposure": "mobile",
        "grouptag": "co2mofetten",
        "integrations": {
            "mqtt": {
                "enabled": false
            }
        },
        "loc": [
            {
                "geometry": {
                    "coordinates": [
                        9.059392,
                        48.527146,
                        341.9
                    ],
                    "timestamp": "2018-08-08T15:26:54.745Z",
                    "type": "Point"
                },
                "type": "Feature"
            }
        ],
        "model": "custom",
        "name": "CO2 Test Box",
        "sensors": [
            {
                "_id": "5b6af9ba9c13510019d4545a",
                "icon": "osem-shock",
                "sensorType": "SenseAir LP8",
                "title": "co2 concentration",
                "unit": "ppm"
            }
        ],
        "updatedAt": "2018-08-08T15:26:54.755Z"
    }
}
```

And here we have the old title `co2 concentration` again.

This seems like a bug to me.

Furthermore, if I want to add new sensors to this box, I think I would have to just leave the sensor ID out of the request to add a new one. But that leaves me with `Sensor with id undefined not found for editing.`.

So how do I:

- update sensor information
- add new sensors (or delete them?)

via the API?

## Background

I am developing a Python package to access the OpenSenseMap API.

**Comment by ubergesundheit** [comment]
The docs are actuallr incomplete. Apologies for that!

Each sensor in the `sensors` array needs additional properties depending on what you want to do with the sensor:
- `"edited": true` if you want to edit the sensor. Needs also the `_id` property. Replaces the current sensor with the supplied one (Specify all properties! `{ _id, title, unit, sensorType, icon }`)
- `"edited": true, "new": true` if you want to add a new sensor
- `"deleted": true` if you want to delete a sensor. . Needs also the `_id` property.

**Comment by nobodyinperson** [comment]
Thanks @ubergesundheit, that works perfectly fine!

I am leaving the closure of this issue to you as the docs definitely need an update here.
