### ISSUE TITLE
Posting a new senseBox with a description

### ISSUE THREAD

**Issue by nobodyinperson** [sensebox/openSenseMap-API#172]
When [posting a new senseBox](https://docs.opensensemap.org/#api-Boxes-postNewBox), it is not possible to directly add a `description`. 

## Expected Behavior

The [post new senseBox](https://docs.opensensemap.org/#api-Boxes-postNewBox) method should also accept a senseBox `description` in its request body.

## Current Behavior

Even when a `description` is sent along with the request, it is not set on the senseBox.

## Steps to Reproduce (for bugs)

Using [`sensemapi`](https://gitlab.com/tue-umphy/python3-sensemapi):

```python
import sensemapi
account=sensemapi.account.SenseMapAccount(
    username=os.environ.get("SENSEMAP_USER"),
    password=os.environ.get("SENSEMAP_PASSWORD"),
    )
box = sensemapi.senseBox.senseBox(
    exposure = "outdoor",
    name="My senseBox",
    current_lat=50.5,
    current_lon=10.1,
    description="DESCRIPTION!!!"
    )                                                                                            
box.new_sensor(
    title="temperature",
    unit="°C",
    type="SHT31",
    icon="osem-temperature-celsius"
    )
print(box.to_api_json(with_id=False))
# {'name': 'My senseBox',
#  'location': {'lat': 50.5, 'lng': 10.1},
#  'description': 'DESCRIPTION!!!', <<<--- the description is here!
#  'exposure': 'outdoor',
#  'sensors': [{'edited': True,
#    'title': 'temperature',
#    'sensorType': 'SHT31',
#    'unit': '°C',
#    'icon': 'osem-temperature-celsius',
#    'new': True}]}
account.new_box(box)
assert box.description # fails, because it was overridden by the API response
```

## Context

I came across this while [teaching my python3-co2logserver](https://gitlab.com/tue-umphy/co2mofetten/python3-co2logserver/merge_requests/12) to redirect received data to the OpenSenseMap.

## Your Environment

* Version used:
* Environment name and version (e.g. Node v8.3.0):
* Server type and version:
* Operating System and version:
* Link to your project:

https://gitlab.com/tue-umphy/co2mofetten/python3-co2logserver/

**Comment by nobodyinperson** [comment]
And the same should be possible for the `weblink`.

**Comment by ubergesundheit** [comment]
This behaviour is intended. We want users to register their stations, then assemble their station and then update the photo and description with their final setup.

**Comment by nobodyinperson** [comment]
Okay.
