### ISSUE TITLE
BBox query Parameter for get all boxes

### ISSUE THREAD

**Issue by SarahLechler** [sensebox/openSenseMap-API#174]
For the general get all boxes query a bounding box parameter should be available to avoid unnecessary data traffic when requesting the boxes.  

Example:
https://api.opensensemap.org/boxes?bbox=:[52.000,7.000,51.000,6.000]

**Comment by mpfeil** [comment]
`bbox` parameter was implemented in commit a4fa1b357536d68a8cdb04d848bd961b0d5ccd6f

will be available in testing environment (https://api.testing.opensensemap.org) in some minutes. Documentation for `bbox` parameter is not online right now.

If you want to play around you can use it the following way:

| Parameter | Type   | Description                                                  |
| --------- | ------ | ------------------------------------------------------------ |
| bbox      | string | A bounding box containing 4 WGS84 coordinates separated  by comata (,). Order is: longitude southwest, latitude southwest,  longitude northeast, latitude northeast. Minimal and maximal values are:  -180, 180 for longitude and -90, 90 for latitude. |

**Comment by noerw** [comment]
Read the documentation carefully and note the order of coordinates...

By specifying `52.144,7.273,51.784,7.856` you span the whole world, exluding your wanted area.
Try `7.2,51,7.8,52`

**Comment by mpfeil** [comment]
Is now live and was released with `v6`
