### ISSUE TITLE
make timestamp truly optional

### ISSUE THREAD

**Issue by PaulReichmuth** [sensebox/openSenseMap-API#185]
Make the Timestamp optional, when posting a value with a position, or change the docs, so that it is discribed to be needed, if posting with a position.

## Expected Behavior
If I post a Value with Position, I shouldn´t need to post the Timestamp with it, especially for TTN, in which this is a real pain to get working

## Current Behavior
So i tried to get a logger working via TTN and LoRa, which loggs the position and current particulate matter to the OpenSenseMap. After days of searching, I found out that my issue was the timestamp, which was stated as optional in the docs, but wasn´t in the API.

##Possible Solution
Either, the Timestamp is made truly optional in the API when posting with a position, or the Timestamp is discribed as needed in the docs.

**Comment by ubergesundheit** [comment]
I suggest you add the needed change to the documentation.

**Comment by PaulReichmuth** [comment]
Will do

**Comment by PaulReichmuth** [comment]
Quick Question, where are the docs located on Github, I can´t find them

**Comment by ubergesundheit** [comment]
Check out the controllers here. The documentation is generated from comments throughout the code..
https://github.com/sensebox/openSenseMap-API/tree/master/packages/api/lib/controllers
