### ISSUE TITLE
Post from non-senseboxes

### ISSUE THREAD

**Issue by ways** [sensebox/openSenseMap-API#187]
I couldn't see this info on github or the website.

Is it ok to register an account and start pushing data from a DIY box, not a sensebox? I have the Nova Fitness SDS011 sensor connected to an ESP and wondered if I should push measurements to you.

**Comment by ubergesundheit** [comment]
sure! openSenseMap is open to everyone!

Check out https://docs.opensensemap.org for our REST API documentation. Please note we have a rate-limit in place, so please use the [`postNewMeasurements`](https://docs.opensensemap.org/#api-Measurements-postNewMeasurements) endpoint.

**Comment by schwukas** [comment]
It would be interesting to know what the actual limits are, just to avoid nasty surprises in the future :)

**Comment by ubergesundheit** [comment]
We're enforcing rate limits on all routes starting with `/boxes` for `POST` requests. Each IP can issue 15 requests per minute before being limited

**Comment by mpfeil** [comment]
Going to close this issue. It was open for some time and @ubergesundheit answered the question. Feel free to open up a new issue or this one if there are more questions.
