### ISSUE TITLE
Config db host is ignored

### ISSUE THREAD

**Issue by chk1** [sensebox/OpenSenseMap-API#24]
https://github.com/sensebox/OpenSenseMap-API/commit/632bec6344520f15432104fe2801cc1805469f7c#diff-0364f57fbff2fabbe941ed20c328ef1aR15

this causes the database host variable from the config to be ignored

**Comment by ubergesundheit** [comment]
Can you point me to the file where the database host ist defined in a config file and where it is used (before the commit 632bec6)

**Comment by mpfeil** [comment]
It was always localhost. There was no config parameter for database host.

But we should add it to https://github.com/sensebox/OpenSenseMap-API/blob/master/config/index.js
