### ISSUE TITLE
"sensor_id" on measurements is wrong

### ISSUE THREAD

**Issue by chk1** [sensebox/OpenSenseMap-API#25]
It appears that measurement object's sensor_id property is wrong, at least in newer measurements. 

How to reproduce:

Query some recent data
```
db.measurements.find({
    createdAt: { 
            $gt: ISODate("2016-02-13 12:00:00.000Z"),
            $lt: ISODate("2016-02-13 13:30:00.000Z") 
    }
})
```

Copy the "sensor_id" and query sensors:

```
db.sensors.find({
    _id: ObjectId("stuff") 
})
```

No results on new measurement `sensor_id`s. Works fine on old measurements.`sensor_id`s.

**Comment by chk1** [comment]
Nevermind, the `sensors` collection is not used anymore and obsolete.

**Comment by ubergesundheit** [comment]
Can it be removed or is there some piece of the stack that relies on the field? I would pledge to remove it to avoid further confusion and less bytes to transfer

**Comment by chk1** [comment]
It's really just a collection in our database, it could be removed I guess. Collections will automatically be created upon registration & data insertion on an empty system, the `sensors` collection is not created as far as I can tell and not present in code anymore.
