### ISSUE TITLE
URGENT: API broken/server down/no data submits possible

### ISSUE THREAD

**Issue by christophfriedrich** [sensebox/OpenSenseMap-API#26]
I just discovered that my box stopped working at 02:44 this morning due to a failing data transmission to the sensebox API. After restarting it's still the same. I checked several other boxes, they too don't have any data since last night, so the error must be on the API side.

**Comment by christophfriedrich** [comment]
The geofs Fachschaft server was unavailable this morning too, so there might have been a wider problem in the uni's network that also affected the OSeM?

**Comment by chk1** [comment]
Working on it

**Comment by ubergesundheit** [comment]
resolved around 2016-04-29 22:50 UTC
