### ISSUE TITLE
OpenSenseMap API GeoJson kompatibel machen

### ISSUE THREAD

**Issue by kgbvax** [sensebox/openSenseMap-API#29]
Es wäre toll wenn die API GeoJson kompatibel wäre, so das man die Box(en) direkt in in GIS oder Webapp stecken könnte.

**Comment by ubergesundheit** [comment]
wird montag deployed..
Danach wird es möglich sein in den routen `/boxes` und `/boxes/<boxid>` mit `format=geojson` eine GeoJSON Featurecollection als response zu kriegen

**Comment by ubergesundheit** [comment]
Now live on api.opensensemap.org

https://api.opensensemap.org/boxes?format=geojson
https://api.opensensemap.org/boxes/55a3a864a807ade00fc7d5ce?format=geojson
