### ISSUE TITLE
include measurement unit in CSV download

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap-API#37]
As a phenomenon may be measured in different units, the sensors unit of measurement should be included in the CSV download (`/boxes/data?...`) to allow proper data evaluation

**Comment by ubergesundheit** [comment]
I am not sure if it makes sense to include up to 1000 times `%` or `hPa` as currently the endpoint only allows to download for one phenomenon (with known unit) anyway.

I could however implement a parameter which enables this behaviour..
