### ISSUE TITLE
Data download fails since february

### ISSUE THREAD

**Issue by Smo-RBR** [sensebox/openSenseMap-API#486]
Hello,

iam running a daily shellscript to download the data from my box to an database. Tody i looked into the database, and saw that since Feb-21 no new data is written. So i checked my script, but nothing is changed. Fired it up by hand, and nothing happens, even not an error message. Has the API changed since February? My compiled curl line is:

curl "https://api.opensensemap.org/boxes/597c4420fe1c740011cbfefb/data/5c0f93f7919bf8001af306dc?from-date=2021-05-28T00:00:00Z&to-date=2021-05-29T00:00:00Z"

Thank you,
Steve

**Comment by umut0** [comment]
Hi Steve,

It seems that your sensor was offline for some duration. If I change the dates in your request I get Data as usually, e.g:
https://api.opensensemap.org/boxes/597c4420fe1c740011cbfefb/data/5c0f93f7919bf8001af306dc?from-date=2021-06-01T00:00:00Z&to-date=2021-06-02T00:00:00Z

There is no Data for the 28th of Mai apparently for the sensor you linked.
You can check the archive too:
https://archive.opensensemap.org/2021-05-28/597c4420fe1c740011cbfefb-Sportplatz_H__rtensdorf/

The API did not change.

Greatings,
Umut
