### ISSUE TITLE
Make use of restify gzip response plugin

### ISSUE THREAD

**Issue by mpfeil** [sensebox/openSenseMap-API#57]
In combination with gzip frontend stuff (https://github.com/sensebox/openSenseMap/issues/148) also gzip api responses if possible

**Comment by ubergesundheit** [comment]
I think this should be handled by the upstream proxy.

**Comment by ubergesundheit** [comment]
The original configuration in https://github.com/sensebox/osem-caddy/blob/master/Caddyfile#L45-47 was disabled in production. gzip is now enabled for api responsed
