### ISSUE TITLE
Bug: `getBoxLocations` return `[]`

### ISSUE THREAD

**Issue by KillerJulian** [sensebox/openSenseMap-API#761]
[getBoxLocations](https://docs.opensensemap.org/#api-Boxes-getBoxLocations) returns empty array when `from-date` is not set.

## Expected Behavior
If `from-date` and `to-date` are not set, all locations should return.
If `to-date` is not set, all locations should return until time.

**Reponse**
```json
[
	{
		"timestamp": "2016-04-02T18:12:23.000Z",
		"coordinates": [
			7.64568,
			51.962372
		],
		"type": "Point"
	}
]
```

## Current Behavior
**Reponse**
```json
[]
```

## Possible Solution
Modify the [filter function](https://github.com/sensebox/openSenseMap-API/blob/2e645bdc4c80e668720b5eaaf384a35d2909569e/packages/models/src/box/box.js#L959C3-L959C3)

## Steps to Reproduce

**Empty result 🐛**
HTTP-GET:
`https://api.opensensemap.org/boxes/57000b8745fd40c8196ad04c/locations`

**Expected result ✔️**
HTTP-GET with set `from-date`:
`https://api.opensensemap.org/boxes/57000b8745fd40c8196ad04c/locations?from-date=2000-01-01T00:00:00.000Z`

**Comment by KillerJulian** [comment]
Same issue if you trying to fetch data on `https://api.opensensemap.org/boxes/57000b8745fd40c8196ad04c/data/57000b8745fd40c8196ad052`without a `to-date`

**Comment by KillerJulian** [comment]
Or is this meant to be like the [Messurements](https://docs.opensensemap.org/#api-Measurements-getData), so that only the last 48 hours are selected if no `from-Date` is set?

**Comment by mpfeil** [comment]
Right now the `/boxes/:boxId/locations` endpoint is working as expected.

### Case 1: No `from-date` and `to-date` specified
If you don´t provide `from-date` and `to-date` both will have default values as specified in the [docs](https://docs.opensensemap.org/#api-Boxes-getBoxLocations)
- `from-date`: Beginning date of location timestamps (default: 48 hours ago from now)
- `to-date`: End date of location timstamps (default: now)

That´s why you get an `[]` empty array as a response.

### Case 2: Just `from-date` specified
If you just provide `from-date` you will get all locations from the specified `from-date` until the default `to-date` (now)

### Case 3: Just `to-date` specified
If you just provide `to-date` the parameter `from-date` is set to 48 hours before the specified `to-date`.
