### ISSUE TITLE
make / show documentation

### ISSUE THREAD

**Issue by niccokunzmann** [sensebox/openSenseMap-API#77]
I was querying the page https://api.opensensemap.org/ 
I expected to see where it is implemented and where I can contribute.

To solve this issue:
Please add a link there for the Github repository. https://github.com/sensebox/openSenseMap-API/

**Comment by ubergesundheit** [comment]
Hi,

there is already an open issue and code which resolves this. (#56)

It will come live when the development branch will be merged into master.

In the mean time, check out https://docs.opensensemap.org for an API reference.

**Comment by niccokunzmann** [comment]
Thanks!
