### ISSUE TITLE
docs: better documentation of return values

### ISSUE THREAD

**Issue by KillerJulian** [sensebox/openSenseMap-API#782]
Hello everyone,
I am the baker of the library [opensensemap-client](https://github.com/KillerJulian/opensensemap-client). It is a connector between TypeScript code and your API endpoints.

As I've been going through her code hand by hand to define the types (it wasn't an easy job), I've noticed that her returns are not consistent. Unfortunately, the documentation doesn't give much information about the returns either.

**One example:**
A [Box](https://killerjulian.github.io/opensensemap-client/types/BoxData.html) contains a array field called `sensors`.
The sensor can have an `lastMeasurement` field.

However, this `lastMeasurement` can now be a [`Measurement`](https://killerjulian.github.io/opensensemap-client/types/Measurement.html), or a [`LastMeasurement`](https://killerjulian.github.io/opensensemap-client/types/LastMeasurement.html) or just an ID of a `Measurement`.

Which data type you get back from the API depends on the APi endpoint.

**Solution approach:**

- Better documentation about the return values
- More consistency for the return values

Please let us find a good solution for their users. Thank you

**Comment by mpfeil** [comment]
Hi @KillerJulian,

thank you for your request. As you have pointed out the `lastMeasurement` property on the sensor schema is a reference to the [measurment schema](https://github.com/sensebox/openSenseMap-API/blob/master/packages/models/src/measurement/measurement.js#L8) and is only populated on specific endpoints and I think it is fine to have different return types for it.

Therefore I would suggest to add examples of the returned values to the documentation using [@apiSuccess](https://apidocjs.com/#param-api-success) and [@apiSuccessExample](https://apidocjs.com/#param-api-success-example)
