### ISSUE TITLE
archive 404

### ISSUE THREAD

**Issue by ChrizKu** [sensebox/openSenseMap-API#85]
dead link archive of sensor.
[example](https://opensensemap.org/explore/58dfdca1f7b1c10011c60fe6):  click the archive icon top right.

the plot could be hard to find (dropdown). perhaps an archive-icon right of the value could give a hint, when the mouse hovers over panel-title/accordion-toggle.

**Comment by ubergesundheit** [comment]
Archive seems to be up. If this occurs again, please open a new issue.

For the suggestion with the graphs, please open an issue in the repository senseBox/openSenseMap [here](https://github.com/sensebox/OpenSenseMap/issues)
