### ISSUE TITLE
Confirmation Link Encoding

### ISSUE THREAD

**Issue by felixerdy** [sensebox/openSenseMap-API#870]
When using an email address with suffix, e.g. `hello+opensensemap@example.com`, the `+` sign is not encoded correctly.

## Expected Behavior
`+` gets encoded to `%2B`

https://opensensemap.org/account/confirm-email?email=hello%2Bopensensemap@example.com&token=xxx

## Current Behavior
`+` gets encoded to ` ` (space)

https://opensensemap.org/account/confirm-email?email=hello opensensemap@example.com&token=xxx

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
A customer notified us about this issue

## Your Environment

* Version used:
* Environment name and version (e.g. Node v8.3.0):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by mpfeil** [comment]
This should be an issue within our `mailer`

**Comment by mpfeil** [comment]
@felixerdy I have fixed this in our `mailer` and deployed it to https://testing.opensensemap.org

Could you verify that it´s encoded correctly?

**Comment by felixerdy** [comment]
Just tested. Seems to be working 🎉 Thank you!

closed in https://github.com/openSenseMap/mailer/pull/77

**Comment by mpfeil** [comment]
Going to create a new version of the `mailer` and will deploy it tomorrow
