### ISSUE TITLE
Feinstaub Addon has PM10 & PM2.5 mixed up

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap-API#88]
Feinstaub addon WiFi sketch submits PM10 Values as PM2.5, and PM2.5 values as PM10.
it's a matter of the order of the sensorIds.

**Comment by ubergesundheit** [comment]
Dang, good catch! Could you please check the Ethernet sketch as well? The order of sensor ids is defined somewhere in https://github.com/sensebox/openSenseMap-API/blob/master/lib/sketches/processWifi.js 
You could also change it there
