### ISSUE TITLE
Überprüfung der Berechnung des UV-Index Wertes

### ISSUE THREAD

**Issue by mpfeil** [sensebox/openSenseMap-API#92]
In der Funktion [getUV](https://github.com/sensebox/openSenseMap-API/blob/master/files/template_home/template_home.ino#L121) wird der gemessene Werte mit `5` multipliziert.

Laut dem [VEML Beispiel](https://github.com/watterott/VEML6070-Breakout/blob/master/software/VEML6070.ino) von Watterott müsste der Wert mit `5.625` multipliziert werden.
Auszug aus dem Beispiel:
```
Integration Times and UVA Sensitivity:
  Rset=240k -> 1T=100.0ms ->   5.000 uW/cm²/step
  Rset=270k -> 1T=112.5ms ->   5.625 uW/cm²/step
  Rset=300k -> 1T=125.0ms ->   6.250 uW/cm²/step
  Rset=600k -> 1T=250.0ms ->  12.500 uW/cm²/step
```

Der `Rset` Wert kann hier nachgeschaut werden: https://github.com/watterott/VEML6070-Breakout/blob/master/hardware/VEML6070-Breakout_v11.pdf

**Comment by janwirwahn** [comment]
Rset=270k -> 1T=112.5ms ->   5.625 uW/cm²/step
